---
title: "LaVoy's Landing Page"
output: 
    html_document:
        theme: "darkly"
---

```{r setup, echo=FALSE} 
library(htmltools)
library(leaflet)
```

# {.tabset}

## Socials

[Github](https://github.com/cyberLaVoy)

[LinkedIn](https://linkedin.com/in/cyberLaVoy)

[Goodreads](https://goodreads.com/cyberLaVoy)

[Twitter](https://twitter.com/cyberLaVoy)

[YouTube](https://www.youtube.com/@cyberLaVoy)

[Instagram](https://www.instagram.com/cyberlavoy/)

## Freeskate

Inline skating destinations I've explored.

The number of destination markers will grow!

```{r, echo=FALSE}
destinations <- data.frame(lat=c(33.89, 37.09),
                           lng=c(-118.42, -113.56), 
                           desc=c("Marvin Braude", "Virgin River"))

m <- leaflet() %>%
    addTiles() %>%
    addMarkers(lng = destinations$lng, lat = destinations$lat, popup = destinations$desc)

m
```

## Blog Posts {.tabset .tabset-pills}

Not really blog posts. More like random tutorials.

### Parsing Web Content
```{r, echo=FALSE}
htmltools::includeMarkdown("blog-posts/2019-11-25-parsing-web-content-with-python.md")
```

### Text-to-Speech
```{r, echo=FALSE}
htmltools::includeMarkdown("blog-posts/2019-12-09-text-to-speech-google-wavenet-with-python.md")
```


## Web Apps

Kind of broken enigmas.

[Monty Hall](web-apps/monty-hall/index.html)

[Controllable Red Square](web-apps/controllable-red-square/index.html)

[Tasks](web-apps/tasks/index.html)
